// Generated by gencpp from file seguimiento/direccionAudio.msg
// DO NOT EDIT!


#ifndef SEGUIMIENTO_MESSAGE_DIRECCIONAUDIO_H
#define SEGUIMIENTO_MESSAGE_DIRECCIONAUDIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace seguimiento
{
template <class ContainerAllocator>
struct direccionAudio_
{
  typedef direccionAudio_<ContainerAllocator> Type;

  direccionAudio_()
    : header()
    , vad(false)
    , doa(0)  {
    }
  direccionAudio_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vad(false)
    , doa(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _vad_type;
  _vad_type vad;

   typedef int32_t _doa_type;
  _doa_type doa;





  typedef boost::shared_ptr< ::seguimiento::direccionAudio_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seguimiento::direccionAudio_<ContainerAllocator> const> ConstPtr;

}; // struct direccionAudio_

typedef ::seguimiento::direccionAudio_<std::allocator<void> > direccionAudio;

typedef boost::shared_ptr< ::seguimiento::direccionAudio > direccionAudioPtr;
typedef boost::shared_ptr< ::seguimiento::direccionAudio const> direccionAudioConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seguimiento::direccionAudio_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seguimiento::direccionAudio_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seguimiento

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'seguimiento': ['/home/disa/catkin_ws/src/seguimiento/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::direccionAudio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::direccionAudio_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::direccionAudio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::direccionAudio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::direccionAudio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::direccionAudio_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seguimiento::direccionAudio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26d1631e5cd32777f7f0538fff298a47";
  }

  static const char* value(const ::seguimiento::direccionAudio_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26d1631e5cd32777ULL;
  static const uint64_t static_value2 = 0xf7f0538fff298a47ULL;
};

template<class ContainerAllocator>
struct DataType< ::seguimiento::direccionAudio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seguimiento/direccionAudio";
  }

  static const char* value(const ::seguimiento::direccionAudio_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seguimiento::direccionAudio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool vad\n\
int32 doa\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seguimiento::direccionAudio_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seguimiento::direccionAudio_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vad);
      stream.next(m.doa);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct direccionAudio_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seguimiento::direccionAudio_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seguimiento::direccionAudio_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vad: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vad);
    s << indent << "doa: ";
    Printer<int32_t>::stream(s, indent + "  ", v.doa);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGUIMIENTO_MESSAGE_DIRECCIONAUDIO_H
