// Generated by gencpp from file seguimiento/ganador.msg
// DO NOT EDIT!


#ifndef SEGUIMIENTO_MESSAGE_GANADOR_H
#define SEGUIMIENTO_MESSAGE_GANADOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace seguimiento
{
template <class ContainerAllocator>
struct ganador_
{
  typedef ganador_<ContainerAllocator> Type;

  ganador_()
    : header()
    , ganador(0)
    , pan(0.0)
    , tilt(0.0)  {
    }
  ganador_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ganador(0)
    , pan(0.0)
    , tilt(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _ganador_type;
  _ganador_type ganador;

   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;





  typedef boost::shared_ptr< ::seguimiento::ganador_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seguimiento::ganador_<ContainerAllocator> const> ConstPtr;

}; // struct ganador_

typedef ::seguimiento::ganador_<std::allocator<void> > ganador;

typedef boost::shared_ptr< ::seguimiento::ganador > ganadorPtr;
typedef boost::shared_ptr< ::seguimiento::ganador const> ganadorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seguimiento::ganador_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seguimiento::ganador_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seguimiento

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'seguimiento': ['/home/disa/catkin_ws/src/seguimiento/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::ganador_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::ganador_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::ganador_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::ganador_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::ganador_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::ganador_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seguimiento::ganador_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acd34bbdf6fbc35f775b9daf437ae7b2";
  }

  static const char* value(const ::seguimiento::ganador_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacd34bbdf6fbc35fULL;
  static const uint64_t static_value2 = 0x775b9daf437ae7b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::seguimiento::ganador_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seguimiento/ganador";
  }

  static const char* value(const ::seguimiento::ganador_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seguimiento::ganador_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 ganador\n\
float32 pan\n\
float32 tilt\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seguimiento::ganador_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seguimiento::ganador_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ganador);
      stream.next(m.pan);
      stream.next(m.tilt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ganador_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seguimiento::ganador_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seguimiento::ganador_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ganador: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ganador);
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGUIMIENTO_MESSAGE_GANADOR_H
