// Generated by gencpp from file seguimiento/puntosCaras.msg
// DO NOT EDIT!


#ifndef SEGUIMIENTO_MESSAGE_PUNTOSCARAS_H
#define SEGUIMIENTO_MESSAGE_PUNTOSCARAS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace seguimiento
{
template <class ContainerAllocator>
struct puntosCaras_
{
  typedef puntosCaras_<ContainerAllocator> Type;

  puntosCaras_()
    : header()
    , numeroCaras(0)
    , x1()
    , y1()
    , x2()
    , y2()
    , puntoX()
    , puntoY()
    , indiceCara()
    , caraNueva()  {
    }
  puntosCaras_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , numeroCaras(0)
    , x1(_alloc)
    , y1(_alloc)
    , x2(_alloc)
    , y2(_alloc)
    , puntoX(_alloc)
    , puntoY(_alloc)
    , indiceCara(_alloc)
    , caraNueva(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _numeroCaras_type;
  _numeroCaras_type numeroCaras;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x1_type;
  _x1_type x1;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y1_type;
  _y1_type y1;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x2_type;
  _x2_type x2;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y2_type;
  _y2_type y2;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _puntoX_type;
  _puntoX_type puntoX;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _puntoY_type;
  _puntoY_type puntoY;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _indiceCara_type;
  _indiceCara_type indiceCara;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _caraNueva_type;
  _caraNueva_type caraNueva;





  typedef boost::shared_ptr< ::seguimiento::puntosCaras_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seguimiento::puntosCaras_<ContainerAllocator> const> ConstPtr;

}; // struct puntosCaras_

typedef ::seguimiento::puntosCaras_<std::allocator<void> > puntosCaras;

typedef boost::shared_ptr< ::seguimiento::puntosCaras > puntosCarasPtr;
typedef boost::shared_ptr< ::seguimiento::puntosCaras const> puntosCarasConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seguimiento::puntosCaras_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seguimiento::puntosCaras_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seguimiento

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'seguimiento': ['/home/disa/catkin_ws/src/seguimiento/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::puntosCaras_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::puntosCaras_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::puntosCaras_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::puntosCaras_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::puntosCaras_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::puntosCaras_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seguimiento::puntosCaras_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9577e30fd5aa6d52d9bd36c0e0026d1";
  }

  static const char* value(const ::seguimiento::puntosCaras_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9577e30fd5aa6d5ULL;
  static const uint64_t static_value2 = 0x2d9bd36c0e0026d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::seguimiento::puntosCaras_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seguimiento/puntosCaras";
  }

  static const char* value(const ::seguimiento::puntosCaras_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seguimiento::puntosCaras_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 numeroCaras\n\
int32[] x1\n\
int32[] y1\n\
int32[] x2\n\
int32[] y2\n\
int32[] puntoX\n\
int32[] puntoY\n\
int32[] indiceCara\n\
bool[] caraNueva\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seguimiento::puntosCaras_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seguimiento::puntosCaras_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.numeroCaras);
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.puntoX);
      stream.next(m.puntoY);
      stream.next(m.indiceCara);
      stream.next(m.caraNueva);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct puntosCaras_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seguimiento::puntosCaras_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seguimiento::puntosCaras_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "numeroCaras: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numeroCaras);
    s << indent << "x1[]" << std::endl;
    for (size_t i = 0; i < v.x1.size(); ++i)
    {
      s << indent << "  x1[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x1[i]);
    }
    s << indent << "y1[]" << std::endl;
    for (size_t i = 0; i < v.y1.size(); ++i)
    {
      s << indent << "  y1[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y1[i]);
    }
    s << indent << "x2[]" << std::endl;
    for (size_t i = 0; i < v.x2.size(); ++i)
    {
      s << indent << "  x2[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x2[i]);
    }
    s << indent << "y2[]" << std::endl;
    for (size_t i = 0; i < v.y2.size(); ++i)
    {
      s << indent << "  y2[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y2[i]);
    }
    s << indent << "puntoX[]" << std::endl;
    for (size_t i = 0; i < v.puntoX.size(); ++i)
    {
      s << indent << "  puntoX[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.puntoX[i]);
    }
    s << indent << "puntoY[]" << std::endl;
    for (size_t i = 0; i < v.puntoY.size(); ++i)
    {
      s << indent << "  puntoY[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.puntoY[i]);
    }
    s << indent << "indiceCara[]" << std::endl;
    for (size_t i = 0; i < v.indiceCara.size(); ++i)
    {
      s << indent << "  indiceCara[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.indiceCara[i]);
    }
    s << indent << "caraNueva[]" << std::endl;
    for (size_t i = 0; i < v.caraNueva.size(); ++i)
    {
      s << indent << "  caraNueva[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.caraNueva[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGUIMIENTO_MESSAGE_PUNTOSCARAS_H
