// Generated by gencpp from file seguimiento/salidaRedCompetitiva.msg
// DO NOT EDIT!


#ifndef SEGUIMIENTO_MESSAGE_SALIDAREDCOMPETITIVA_H
#define SEGUIMIENTO_MESSAGE_SALIDAREDCOMPETITIVA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace seguimiento
{
template <class ContainerAllocator>
struct salidaRedCompetitiva_
{
  typedef salidaRedCompetitiva_<ContainerAllocator> Type;

  salidaRedCompetitiva_()
    : header()
    , data()  {
    }
  salidaRedCompetitiva_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> const> ConstPtr;

}; // struct salidaRedCompetitiva_

typedef ::seguimiento::salidaRedCompetitiva_<std::allocator<void> > salidaRedCompetitiva;

typedef boost::shared_ptr< ::seguimiento::salidaRedCompetitiva > salidaRedCompetitivaPtr;
typedef boost::shared_ptr< ::seguimiento::salidaRedCompetitiva const> salidaRedCompetitivaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seguimiento

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'seguimiento': ['/home/disa/catkin_ws/src/seguimiento/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a120344537a3b099cc9ec9957d4619fc";
  }

  static const char* value(const ::seguimiento::salidaRedCompetitiva_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa120344537a3b099ULL;
  static const uint64_t static_value2 = 0xcc9ec9957d4619fcULL;
};

template<class ContainerAllocator>
struct DataType< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seguimiento/salidaRedCompetitiva";
  }

  static const char* value(const ::seguimiento::salidaRedCompetitiva_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[] data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seguimiento::salidaRedCompetitiva_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct salidaRedCompetitiva_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seguimiento::salidaRedCompetitiva_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seguimiento::salidaRedCompetitiva_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGUIMIENTO_MESSAGE_SALIDAREDCOMPETITIVA_H
