// Generated by gencpp from file seguimiento/siguelinea.msg
// DO NOT EDIT!


#ifndef SEGUIMIENTO_MESSAGE_SIGUELINEA_H
#define SEGUIMIENTO_MESSAGE_SIGUELINEA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace seguimiento
{
template <class ContainerAllocator>
struct siguelinea_
{
  typedef siguelinea_<ContainerAllocator> Type;

  siguelinea_()
    : header()
    , distancia(0.0)
    , angulo(0.0)  {
    }
  siguelinea_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distancia(0.0)
    , angulo(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _distancia_type;
  _distancia_type distancia;

   typedef float _angulo_type;
  _angulo_type angulo;





  typedef boost::shared_ptr< ::seguimiento::siguelinea_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seguimiento::siguelinea_<ContainerAllocator> const> ConstPtr;

}; // struct siguelinea_

typedef ::seguimiento::siguelinea_<std::allocator<void> > siguelinea;

typedef boost::shared_ptr< ::seguimiento::siguelinea > siguelineaPtr;
typedef boost::shared_ptr< ::seguimiento::siguelinea const> siguelineaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seguimiento::siguelinea_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seguimiento::siguelinea_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seguimiento

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'seguimiento': ['/home/disa/catkin_ws/src/seguimiento/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::siguelinea_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seguimiento::siguelinea_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::siguelinea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seguimiento::siguelinea_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::siguelinea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seguimiento::siguelinea_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seguimiento::siguelinea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ba4eeb657900659451097c3c7c247d9";
  }

  static const char* value(const ::seguimiento::siguelinea_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ba4eeb657900659ULL;
  static const uint64_t static_value2 = 0x451097c3c7c247d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::seguimiento::siguelinea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seguimiento/siguelinea";
  }

  static const char* value(const ::seguimiento::siguelinea_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seguimiento::siguelinea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 distancia\n\
float32 angulo\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seguimiento::siguelinea_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seguimiento::siguelinea_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distancia);
      stream.next(m.angulo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct siguelinea_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seguimiento::siguelinea_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seguimiento::siguelinea_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distancia: ";
    Printer<float>::stream(s, indent + "  ", v.distancia);
    s << indent << "angulo: ";
    Printer<float>::stream(s, indent + "  ", v.angulo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGUIMIENTO_MESSAGE_SIGUELINEA_H
