// Generated by gencpp from file avatar_msg/center_face.msg
// DO NOT EDIT!


#ifndef AVATAR_MSG_MESSAGE_CENTER_FACE_H
#define AVATAR_MSG_MESSAGE_CENTER_FACE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avatar_msg
{
template <class ContainerAllocator>
struct center_face_
{
  typedef center_face_<ContainerAllocator> Type;

  center_face_()
    : center_x(0.0)
    , center_y(0.0)  {
    }
  center_face_(const ContainerAllocator& _alloc)
    : center_x(0.0)
    , center_y(0.0)  {
  (void)_alloc;
    }



   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;





  typedef boost::shared_ptr< ::avatar_msg::center_face_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avatar_msg::center_face_<ContainerAllocator> const> ConstPtr;

}; // struct center_face_

typedef ::avatar_msg::center_face_<std::allocator<void> > center_face;

typedef boost::shared_ptr< ::avatar_msg::center_face > center_facePtr;
typedef boost::shared_ptr< ::avatar_msg::center_face const> center_faceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avatar_msg::center_face_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avatar_msg::center_face_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace avatar_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'avatar_msg': ['/home/disa/catkin_ws/src/avatar_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::avatar_msg::center_face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avatar_msg::center_face_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avatar_msg::center_face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avatar_msg::center_face_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avatar_msg::center_face_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avatar_msg::center_face_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avatar_msg::center_face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c51e51b1031fa051202f8de7f01927c6";
  }

  static const char* value(const ::avatar_msg::center_face_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc51e51b1031fa051ULL;
  static const uint64_t static_value2 = 0x202f8de7f01927c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::avatar_msg::center_face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avatar_msg/center_face";
  }

  static const char* value(const ::avatar_msg::center_face_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avatar_msg::center_face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 center_x\n\
float32 center_y\n\
";
  }

  static const char* value(const ::avatar_msg::center_face_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avatar_msg::center_face_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.center_x);
      stream.next(m.center_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct center_face_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avatar_msg::center_face_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avatar_msg::center_face_<ContainerAllocator>& v)
  {
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVATAR_MSG_MESSAGE_CENTER_FACE_H
