// Generated by gencpp from file avatar_msg/decir.msg
// DO NOT EDIT!


#ifndef AVATAR_MSG_MESSAGE_DECIR_H
#define AVATAR_MSG_MESSAGE_DECIR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avatar_msg
{
template <class ContainerAllocator>
struct decir_
{
  typedef decir_<ContainerAllocator> Type;

  decir_()
    : palabras()  {
    }
  decir_(const ContainerAllocator& _alloc)
    : palabras(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _palabras_type;
  _palabras_type palabras;





  typedef boost::shared_ptr< ::avatar_msg::decir_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avatar_msg::decir_<ContainerAllocator> const> ConstPtr;

}; // struct decir_

typedef ::avatar_msg::decir_<std::allocator<void> > decir;

typedef boost::shared_ptr< ::avatar_msg::decir > decirPtr;
typedef boost::shared_ptr< ::avatar_msg::decir const> decirConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avatar_msg::decir_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avatar_msg::decir_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace avatar_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'avatar_msg': ['/home/disa/catkin_ws/src/avatar_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::avatar_msg::decir_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avatar_msg::decir_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avatar_msg::decir_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avatar_msg::decir_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avatar_msg::decir_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avatar_msg::decir_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avatar_msg::decir_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f31a5a411200c463cdcdb46c34aa2c72";
  }

  static const char* value(const ::avatar_msg::decir_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf31a5a411200c463ULL;
  static const uint64_t static_value2 = 0xcdcdb46c34aa2c72ULL;
};

template<class ContainerAllocator>
struct DataType< ::avatar_msg::decir_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avatar_msg/decir";
  }

  static const char* value(const ::avatar_msg::decir_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avatar_msg::decir_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string palabras\n\
";
  }

  static const char* value(const ::avatar_msg::decir_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avatar_msg::decir_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.palabras);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct decir_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avatar_msg::decir_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avatar_msg::decir_<ContainerAllocator>& v)
  {
    s << indent << "palabras: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.palabras);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVATAR_MSG_MESSAGE_DECIR_H
