(cl:defpackage seguimiento-msg
  (:use )
  (:export
   "<ARRAYFLOAT>"
   "ARRAYFLOAT"
   "<AUDIODETECTADO>"
   "AUDIODETECTADO"
   "<DIRECCIONAUDIO>"
   "DIRECCIONAUDIO"
   "<ENTRADAKALMAN>"
   "ENTRADAKALMAN"
   "<ENTRADAREDCOMPETITIVA>"
   "ENTRADAREDCOMPETITIVA"
   "<GANADOR>"
   "GANADOR"
   "<NIVELAUDIO>"
   "NIVELAUDIO"
   "<PUNTOSCARAS>"
   "PUNTOSCARAS"
   "<SALIDAKALMAN>"
   "SALIDAKALMAN"
   "<SALIDAREDCOMPETITIVA>"
   "SALIDAREDCOMPETITIVA"
   "<SIGUELINEA>"
   "SIGUELINEA"
  ))

